figma:
  token: "your_figma_token"
  file_keys:
    - "file_key1"
    - "file_key2"

schedule: "0 9 * * *"  # Every day at 09:00 UTC

email:
  smtp_host: "smtp.example.com"
  smtp_port: 587
  smtp_username: "user@example.com"
  smtp_password: "password"
  from: "noreply@example.com"
  to:
    - "user1@example.com"
    - "user2@example.com"
  subject: "Figma Comments Report"
  body: "Attached is the latest Figma comments report."

  report:
  # Export fields
  fields:
    - name: "file_name"
      display: "File Name"
    - name: "file_id"
      display: "File ID"
    - name: "node_name"
      display: "Node Name"
    - name: "node_id"
      display: "Node ID"
    - name: "message"
      display: "Comment"
    - name: "author"
      display: "Author"
    - name: "created_at"
      display: "Created At"
      format: "2006-01-02 15:04"
    - name: "status"
      display: "Status"
    - name: "resolved_at"
      display: "Resolved At"
      format: "2006-01-02 15:04"
    - name: "link"
      display: "Link"